### PR TITLE
added building data

### PR DESCRIPTION
**Pull request by ccMatrix**
some buildings are still missing some levels. Especially Armory and some generators that get unlocked in higher levels.

### CODE REVIEW

**Comment by ccMatrix** [comment]
The schema in buildings did not require the bonus values to be full integers. Do we want to use percentage values as 1.0 = 100% or is 100 = 100% ?

**Comment by Iliasgx** [comment]
> The schema in buildings did not require the bonus values to be full integers. Do we want to use percentage values as 1.0 = 100% or is 100 = 100% ?

The bonuses are stored as `number`, not `integer`. Therefore `100%` will be stored as `1.0`.

As the example below shows, bonuses store wether it will be a percentage or not. Storting the values as such follows the normal percentage formatting rules.

`"bonus1": {
      "name": "repair speed bonus",
      "percentage": true
    },
    "bonus2": {
      "name": "repair cost efficiency",
      "percentage": true
    }`

**Comment by ccMatrix** [comment]
I was coding it the same way expecting 1.0 = 100%. But the research schema suddenly wanted integer values so I got confused which way was the way to go. Can you update the schema for research to use number instead of integer and I'll generate the json files with that in mind?

**Review by WebSpider — APPROVED** [review]
Thank you for this huge contribution!

**Pull request merged**
