### PR TITLE
systems

### PR DESCRIPTION
**Pull request by ccMatrix**
initial work on systems. json does not fit with schema. let's talk about the info we need in there and then update the schema accordingly.

- token stuff moved to locked_by which can be either an item or a mission
- system_type can be route, terminal or hub.
- system_space was tricky because the old data is strange. some are both origin sector and deepspace which doesn't make sense to me. All origin sector systems were also marked as deepspace yes. I currently map those to origin sector only,
- mining (maybe change name?) is an array of the types of mines and includes an optional field with `grade` that is populated for materials and isogen. Data includes type, amount, grade, mining_per_hour and the size of the mine.
- system description is available only for some systems others have empty string there
- for origin sector the systems include the capture_nodes info but not much else since there is also the territories schema that would include info like the takeover times so I did not parse them into the systems.

### CODE REVIEW

**Comment by ccMatrix** [comment]
> Is there a method you use to translate system names to filename-safe? I've been using slugify() from Django, but that renders `P'Jem` into `pjem`

I actually wrote my own. It just replaces all characters that are neither number nor letter to an underscore and then reduces multiple underscores to a single one.

**Comment by ccMatrix** [comment]
> A reference to present hostiles and/or armadas is missing here. Is that reference present in the hostile and/or armada definitions? This is in general, not specific to this system

Armadas and hostiles both have a list of systems where they occur. So you could use that info to lookup hostiles and armadas for systems.

**Comment by ccMatrix** [comment]
> P'Jem actually has nodes of a flipping size, both 8500 and 18000. Is this information in source?

Doesn't look like it. P'Jem just says 24 x 18000

**Comment by WebSpider** [comment]
> I expected the lock to be entry only. So if B has a lock then A -> B would need the mission or token while B-> A would not. So far I only saw warp distance requirements and no info about the distance to calculate the shortest distance between systems and apply the warp speed of the ship. I didn't want to duplicate info from the system here. But can't get more connection info from the data :(

Yeah, this was in the `!route` command, I dont think anyone captured that

**Comment by ccMatrix** [comment]
> > I expected the lock to be entry only. So if B has a lock then A -> B would need the mission or token while B-> A would not. So far I only saw warp distance requirements and no info about the distance to calculate the shortest distance between systems and apply the warp speed of the ship. I didn't want to duplicate info from the system here. But can't get more connection info from the data :(
> 
> Yeah, this was in the `!route` command, I dont think anyone captured that

I have some output from `!route` and also for nearest system. There are some infos in there but I don't know if all connections are available.

Example of such a path:
```
From              To               Warp
---------------------------------------
Tholus Alpha (40) Tezera Alpha (30)   5
Tezera Alpha (30) Tezera Beta (30)    5
Tezera Beta (30)  Adia Beta (20)      5
Adia Beta (20)    Temeri Alpha (20)   5
Temeri Alpha (20) Temeri Beta (20)    5
Temeri Beta (20)  Perim Alpha (20)    5
Perim Alpha (20)  Perim Beta (20)     5
Perim Beta (20)   Zorga (2)          20
Zorga (2)         Vinland (4)         2
Vinland (4)       Tellun (7)          5
Tellun (7)        Solusta (7)         5
Solusta (7)       Rua (8)             5
Rua (8)           Grenfil (9)         5
Grenfil (9)       Nausicaa (12)       8
Nausicaa (12)     Nelve (12)          8
Rigel (13)        Zaurak (13)        11
Zaurak (13)       Vindemiatrix (15)  11
Vindemiatrix (15) Krah'Hor (18)      13
Krah'Hor (18)     Azha (20)          13
Azha (20)         Khitomer (23)      17
Khitomer (23)     Yadow (25)         18
Yadow (25)        Enthra (27)        19
Enthra (27)       Morska (29)        20
Morska (29)       Beta Penthe (34)   33
Beta Penthe (34)  Quv'lw (36)        37
Quv'lw (36)       Mempa (38)         39
Mempa (38)        Lankal (39)        40
Lankal (39)       Pheben (39)        61
Pheben (39)       Balduk (39)        52
Balduk (39)       YoDSutlj NaQ (39)  53
---------------------------------------
```

**Comment by WebSpider** [comment]
Lets add the routing information at a later stage, it's no use having a feature that works for a very small subset of routes

**Comment by WebSpider** [comment]
I'll mark grade optional, and get the routing system type added

**Comment by ccMatrix** [comment]
> I'll mark grade optional, and get the routing system type added

I've updated the schema inside the PR branch :)

**Review by WebSpider — APPROVED** [review]
Thanks  for the huge contribution!

**Pull request merged**
