### PR TITLE
added research data

### PR DESCRIPTION
**Pull request by ccMatrix**

### CODE REVIEW

**Comment by WebSpider** [comment]
You should run pre-commit as indicated in https://github.com/STFCcommunity/data#contribution. When you push changes to your branch, bots will try to validate again.

**Comment by davejames** [comment]
Can you please rebase? There shouldn't be any conflicts, and this will pull in the pre-commit files and allow you to run it locally.

Also my apologies but I moved the location of the data files, they are now under a subdirectory called data. I did this so that we could loop through that directory and know it contained only data files and not have to make special allowances for the schema, also aesthetic reasons. The JSON validation action is expecting to see the data files there. Can you please add a commit to move the files?

**Comment by WebSpider** [comment]
@ccMatrix I have updated the actions settings to only require approval if you're new to GitHub. this should make stuff *much* quicker. Apologies, new repo, new settings.

**Comment by WebSpider** [comment]
Seems only the bonuses being mandatory is causing this fail now

**Review by WebSpider — APPROVED** [review]
Lgtm!

**Pull request merged**
