### PR TITLE
Create missions data

### PR DESCRIPTION
**Pull request by Iliasgx**

### CODE REVIEW

**Comment by Iliasgx** [comment]
This data was parsed from the lcars output. We can check the spreadsheet from McMCavemen for missing missions.

**Comment by WebSpider** [comment]
👍
I've seen quite a few files with 0 size. Parser failed?

**Comment by Iliasgx** [comment]
> 👍
> I've seen quite a few files with 0 size. Parser failed?

That's odd, I checked the uploaded files and the smallest size are these: https://cdn.discordapp.com/attachments/869657307955490817/886943729057923092/Schermafbeelding_2021-09-13_om_13.57.38.png

Perhaps GitHub rounds them down?

**Comment by WebSpider** [comment]
Yup, it's a bug in the mobile web interface of github

**Review by WebSpider — APPROVED** [review]
Lgtm

**Pull request merged**
