### PR TITLE
Officers data

### PR DESCRIPTION
**Pull request by ccMatrix**
information and images of all the officers

### CODE REVIEW

**Comment by WebSpider** [comment]
Only 3 officers have issues left 🥳

**Review by WebSpider — CHANGES_REQUESTED** [review]
This PR still has changes in it that were already merged in #15 . Can you please rebase this PR?
?

**Comment by ccMatrix** [comment]
I've rebased this on the latest main and force pushed the branch with just the added officer data

**Review by WebSpider — APPROVED** [review]
lgtm!
Thanks for another awesome contribution!

**Pull request merged**
