### PR TITLE
Added additional fields and schema checks

### PR DESCRIPTION
**Pull request by Iliasgx**
Most of the changes are already included in the ship data from #21

- `Description` is added
- `Buff type` is added as optional
- Ship ability has now the `percentage` attribute
- Component additional info has now checks for all types of components. (Only small changes needed in the data)
- `Quantity` replaces `id`
- Extra check for `required_shipyard_level` if `scrappable = true` (pre-commit split if-then statement unfortunately for easy reading..)

### CODE REVIEW

**Review by WebSpider — CHANGES_REQUESTED** [review]
Please rename to 'scrappable'

The ship doesn't get scraped, it gets scrapped

**Comment by Iliasgx** [comment]
> Please rename to 'scrappable'
> 
> The ship doesn't get scraped, it gets scrapped

Didn't saw that. Could fix that tonight.

**Comment by WebSpider** [comment]
Thats fine :+1:

**Review by WebSpider — COMMENTED** [review]
Is the initial build cost actually different from the added component cost at t1?

**Review by WebSpider — APPROVED** [review]

**Comment by Iliasgx** [comment]
> Is the initial build cost actually different from the added component cost at t1?

Components at T1 will have a `NIL` value in the screens since we don't know how the total cost is split into the components. Therefore, the total build costs are stored in this field. The field is only used for T1.

**Comment by WebSpider** [comment]
@Iliasgx CI is failing on this one

**Comment by Iliasgx** [comment]
The build_cost added on the the ship level should go to initial_build_cost and the details in additional_info should be styled with the new field requirements.

**Review by WebSpider — APPROVED** [review]
lgtm

**Review by WebSpider — COMMENTED** [review]
While fixing a merge conflict inside botany_bay.json, I found the "percentage" field, doesnt correspond with the text. Didnt change it.

**Comment by Iliasgx** [comment]
> While fixing a merge conflict inside botany_bay.json, I found the "percentage" field, doesnt correspond with the text. Didnt change it.

Did you mean the value changed? The value should be true, not false as indicated in the ship data.

**Comment by WebSpider** [comment]
Yeah, the bb description mentioned a percentage, and right under it a property saying percentage = false :smile:

**Comment by Iliasgx** [comment]
The percentage is already fixed in this PR.

**Review by WebSpider — APPROVED** [review]
lgtm

**Pull request merged**
